files:
  include: '**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  no-color-keywords: 1
  no-color-literals: 1
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: true
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-transition-all: 0
  no-url-protocols: 1
  no-vendor-prefixes: 1
  no-warn: 1
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 1
  force-pseudo-nesting: 1

  # Name Formats
  class-name-format:
    - 1
    -
      allow-leading-underscore: false
  function-name-format:
    - 1
    -
      allow-leading-underscore: false
  id-name-format:
    - 1
    -
      allow-leading-underscore: false
  mixin-name-format:
    - 1
    -
      allow-leading-underscore: false
  placeholder-name-format:
    - 1
    -
      allow-leading-underscore: false
  variable-name-format:
    - 1
    -
      allow-leading-underscore: false

  # Style Guide
  bem-depth: 0
  border-zero: 0
  brace-style: 1
  clean-import-paths: 1
  empty-args: 0
  hex-length: 0
  hex-notation: 1
  indentation: 1
  leading-zero:
    - 1
    -
      include: true
  nesting-depth:
    - 1
    -
      max-depth: 4
  property-sort-order:
    - 1
    -
      order: 'smacss'
  quotes: 1
  shorthand-values:
    - 1
    -
      allowed-shorthands:
        - 1
        - 2
  url-quotes: 1
  variable-for-property: 0
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
